EBISPOT/gwas-sumstats-service

sumstats_service/app.py
sumstats_service/resources/api_endpoints.py
sumstats_service/resources/api_utils.py
sumstats_service/resources/mongo_client.py
sumstats_service/resources/payload.py
tests/conftest.py
tests/test_app.py
tests/test_payload.py

Reverts EBISPOT/gwas-sumstats-service#97

Revert "async post request"

---

.gitignore
.gitlab-ci.yml
sumstats_service/config.py

Part of https://github.com/EBISPOT/goci/issues/1179

feat: SLURM Migration

---

.gitignore
.gitlab-ci.yml
sumstats_service/config.py

Part of https://github.com/EBISPOT/goci/issues/1179

Merge dev to master

---

.gitlab-ci.yml

- fix: Add to deploy_staging_workers' script
- fix: Use WORKER_DIR as working dir in deploy_prod_workers' script

fix: Correct Gitlab CI

---

requirements.txt
sumstats_service/resources/convert_meta.py

Change the meta-yaml file output format in convert_meta.py

New yaml from master

---

celery_worker_scripts/dev/START_CELERY_WORKERS_SLURM.sh
celery_worker_scripts/dev/start_celery_worker_slurm.sh
celery_worker_scripts/prod/START_CELERY_WORKERS_SLURM.sh
celery_worker_scripts/prod/start_celery_worker_slurm.sh

fix: SLURM error

---

sumstats_service/resources/api_utils.py

fix: Skip if ftp unavailable

---

sumstats_service/resources/api_utils.py

fix: Use accession id in filename if ftp unavailable

---

sumstats_service/resources/api_utils.py

fix: Add fallback metadata filename

---

requirements.txt
sumstats_service/resources/api_utils.py

fix: Let sumstats-tools handle trait business

---

sumstats_service/resources/api_utils.py

fix: Remove fallback naming for metadata yaml

---

sumstats_service/app.py

https://github.com/EBISPOT/goci/issues/1279

fix: Options parsing in POST endpoint

---

sumstats_service/resources/mongo_client.py

Fix `file_type` issue in https://github.com/EBISPOT/goci/issues/1279

fix: Sort metadata entries by id desc

---

sumstats_service/app.py
sumstats_service/resources/api_utils.py

- Add debug logs. 
- Return failed results rather than None.

fix: Save failed studies status to db

---

workflows/process_submission.nf

https://github.com/EBISPOT/goci/issues/1285
https://github.com/EBISPOT/gwas-sumstats-service/issues/314

fix: Increase mem and time constraints for validation

---

requirements.txt
sumstats_service/resources/api_utils.py

https://github.com/EBISPOT/goci/issues/1292

fix: Bump gwas-sumstats-tools v1.0.17

---

sumstats_service/app.py
sumstats_service/resources/file_handler.py

https://github.com/EBISPOT/goci/issues/1292 - Item 1.

fix: Celery gets stuck at wait calls

---

sumstats_service/resources/api_utils.py

https://github.com/EBISPOT/goci/issues/1306

fix: Folders on staging for GCSTs without sumstats

---

sumstats_service/resources/api_utils.py

https://github.com/EBISPOT/goci/issues/1306

fix: Folders on staging for GCSTs without sumstats (#325)

---

sumstats_service/resources/api_utils.py

* fix: Edge folders e.g. GCST90428000
* fix: Folders with 6 digits
* refactor: Simplify the code

fix: Public FTP path logic for YAML updates (#333)

---

sumstats_service/app.py
sumstats_service/resources/api_utils.py

Issue Description: https://github.com/EBISPOT/goci/issues/1309
- Use triggering task failure for Celery
- Raise exceptions in Celery tasks rather than returning `False`

fix: Silent errors in sumstats pipeline

---

sumstats_service/resources/api_utils.py

* fix: Silent errors in sumstats pipeline
* fix: Add more ctx to emails
* refactor: No need for RuntimeError
* fix: Undefined gcst_id

fix: Silent errors in sumstats pipeline (#341)

---

requirements.txt

https://github.com/EBISPOT/goci/issues/1226
https://github.com/EBISPOT/gwas-sumstats-tools/pull/41

fix: Bump gwas-sumstats-tools to v1.0.20

---

sumstats_service/app.py
sumstats_service/config.py
sumstats_service/resources/api_utils.py
sumstats_service/resources/mongo_client.py

https://github.com/EBISPOT/goci/issues/1309

feat: Send nightly emails for YAML task failures

---

sumstats_service/app.py
sumstats_service/resources/api_utils.py

https://github.com/EBISPOT/goci/issues/1358

fix: Set file type "Non-GWAS-SSF" when force valid

---

sumstats_service/resources/api_utils.py

Fix for GCST003371 and GCST003372 at https://github.com/EBISPOT/goci/issues/1479

fix: Do not filter local files by GCST ID

---

sumstats_service/resources/api_utils.py

https://github.com/EBISPOT/goci/issues/1490

refactor: Revert md5sum compare changes

---

requirements.txt
tox.ini

https://github.com/EBISPOT/goci/issues/1509#issuecomment-2736270985

chore: Bump gwas-sumstats-tools version v1.0.23

---

sumstats_service/resources/mongo_client.py

https://github.com/EBISPOT/gwas-sumstats-service/issues/392

fix: Set pending yaml generation attempts to 0

---

sumstats_service/app.py

https://github.com/EBISPOT/goci/issues/1647

fix: Don't skip yaml generation unless sumstats=NR

---

sumstats_service/app.py
sumstats_service/config.py
sumstats_service/resources/mongo_client.py

https://github.com/EBISPOT/gwas-sumstats-service/issues/382

feat: File type update endpoint

---

.gitignore
sumstats_service/app.py
sumstats_service/resources/api_endpoints.py
sumstats_service/resources/api_utils.py
sumstats_service/resources/mongo_client.py
sumstats_service/resources/study_service.py

Regarding test case 2 at https://github.com/EBISPOT/goci/issues/1647

Fix yaml gen case 2
